apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-argo
  labels:
    app: nginx
spec:
  replicas: 2  # Number of desired pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Use the latest official Nginx image
        ports:
        - containerPort: 80  # Expose port 80
